export const INPUT_CHANGE = "INPUT_CHANGE";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAILURE = "GET_ROLES_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const CLEAR_FORM = "CLEAR_FORM";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_FAILURE = "PASSWORD_CHANGE_FAILURE";
export const PASSWORD_CHANGE_FROM_PROFILE_SUCCESS = "PASSWORD_CHANGE_FROM_PROFILE_SUCCESS";
export const PASSWORD_CHANGE_FROM_PROFILE_FAILURE = "PASSWORD_CHANGE_FROM_PROFILE_FAILURE";
export const SOCIAL_LOGIN_UPDATE_SUCCESS = "SOCIAL_LOGIN_UPDATE_SUCCESS";
export const SOCIAL_LOGIN_UPDATE_FAILURE = "SOCIAL_LOGIN_UPDATE_FAILURE";
export const COURSE_ENROLMENT_SUCCESS = "COURSE_ENROLMENT_SUCCESS";
export const COURSE_ENROLMENT_FAILURE = "COURSE_ENROLMENT_FAILURE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const COURSE_INPUT_CHANGE = "COURSE_INPUT_CHANGE";
export const GET_ALL_COURSES_SUCCESS = "GET_ALL_COURSES_SUCCESS";
export const GET_ALL_COURSES_FAILURE = "GET_ALL_COURSES_FAILURE";
export const GET_SINGLE_COURSE_SUCCESS = "GET_SINGLE_COURSE_SUCCESS";
export const GET_SINGLE_COURSE_FAILURE = "GET_SINGLE_COURSE_FAILURE";
export const POPULATE_DASHBOARD_SUCCESS = "POPULATE_DASHBOARD_SUCCESS";
export const POPULATE_DASHBOARD_FAILURE = "POPULATE_DASHBOARD_FAILURE";

export const PAYMENT_INPUT_CHANGE = "PAYMENT_INPUT_CHANGE";
export const GET_PAYMENT_PLANS_SUCCESS = "GET_PAYMENT_PLANS_SUCCESS";
export const GET_PAYMENT_PLANS_FAILURE = "GET_PAYMENT_PLANS__FAILURE";
export const CREATE_PAYMENT_TRANSACTION_SUCCESS =
  "CREATE_PAYMENT_TRANSACTION_SUCCESS";
export const CREATE_PAYMENT_TRANSACTION_FAILURE =
  "CREATE_PAYMENT_TRANSACTION_FAILURE";

export const LOAD_QUESTIONS_SUCCESS = "LOAD_QUESTIONS_SUCCESS";
export const LOAD_QUESTIONS_FAILURE = "LOAD_QUESTIONS_FAILURE";
export const PAST_QUESTIONS_INPUT_CHANGE = "PAST_QUESTIONS_INPUT_CHANGE";
export const GET_PAST_QUESTION_SUBJECTS_SUCCESS =
  "GET_PAST_QUESTION_SUBJECTS_SUCCESS";
export const GET_PAST_QUESTION_SUBJECTS_FAILURE =
  "GET_PAST_QUESTION_SUBJECTS_FAILURE";
export const FLAG_QUESTION_SUCCESS = "FLAG_QUESTION_SUCCESS";
export const FLAG_QUESTION_FAILURE = "FLAG_QUESTION_FAILURE";
export const SAVE_USER_ANSWER = "SAVE_USER_ANSWER";
export const UPDATE_QUESTION_TAG = "UPDATE_QUESTION_TAG";
export const POPULATE_SUBMITTED_ANSWER = "POPULATE_SUBMITTED_ANSWER";
export const SUBMIT_RESULT_SUCCESS = "SUBMIT_RESULT_SUCCESS";
export const SUBMIT_RESULT_FAILURE = "SUBMIT_RESULT_FAILURE";

export const GET_SUBJECT_AND_RELATED_LESSONS_SUCCESS =
  "GET_SUBJECT_AND_RELATED_LESSONS_SUCCESS";
export const GET_SUBJECT_AND_RELATED_LESSONS_FAILURE =
  "GET_SUBJECT_AND_RELATED_LESSONS_FAILURE";

export const GET_SINGLE_CLASS_SUCCESS = "GET_SINGLE_CLASS_SUCCESS";
export const GET_SINGLE_CLASS_FAILURE = "GET_SINGLE_CLASS_FAILURE";

export const GET_CLASSES_SUCCESS = "GET_CLASSES_SUCCESS";
export const GET_CLASSES_FAILURE = "GET_CLASSES_FAILURE";

export const CREATE_COMMENT_TO_ANNOUNCEMENT_SUCCESS =
  "CREATE_COMMENT_TO_ANNOUNCEMENT_SUCCESS";
export const CREATE_COMMENT_TO_ANNOUNCEMENT_FAILURE =
  "CREATE_COMMENT_TO_ANNOUNCEMENT_FAILURE";

export const ADD_ANNOUNCEMENT_SUCCESS =
  "ADD_ANNOUNCEMENT_SUCCESS";
export const ADD_ANNOUNCEMENT_FAILURE =
  "ADD_ANNOUNCEMENT_FAILURE";

export const CREATE_COMMENT_TO_CONTENT_SUCCESS =
  "CREATE_COMMENT_TO_CONTENT_SUCCESS";
export const CREATE_COMMENT_TO_CONTENT_FAILURE =
  "CREATE_COMMENT_TO_CONTENT_FAILURE";

export const ASSIGN_CONTENT_TO_STUDENT_FAILURE =
  "ASSIGN_CONTENT_TO_STUDENT_FAILURE";
export const ASSIGN_CONTENT_TO_STUDENT_SUCCESS =
  "ASSIGN_CONTENT_TO_STUDENT_SUCCESS";

export const SEND_CLASS_REQUEST_SUCCESS = "SEND_CLASS_REQUEST_SUCCESS";
export const SEND_CLASS_REQUEST_FAILURE = "SEND_CLASS_REQUEST_FAILURE";

export const SEND_CLASS_INVITE_SUCCESS = "SEND_CLASS_INVITE_SUCCESS";
export const SEND_CLASS_INVITE_FAILURE = "SEND_CLASS_INVITE_FAILURE";

export const CHECK_USER_AND_JOIN_CLASS_SUCCESS =
  "CHECK_USER_AND_JOIN_CLASS_SUCCESS";
export const CHECK_USER_AND_JOIN_CLASS_FAILURE =
  "CHECK_USER_AND_JOIN_CLASS_FAILURE";

export const USER_JOIN_THROUGH_INVITE_SUCCESS =
  "USER_JOIN_THROUGH_INVITE_SUCCESS";
export const USER_JOIN_THROUGH_INVITE_FAILURE =
  "USER_JOIN_THROUGH_INVITE_FAILURE";

export const GET_ALL_SEARCH_RESULTS_SUCCESS = "GET_ALL_SEARCH_RESULTS_SUCCESS";
export const GET_ALL_SEARCH_RESULTS_FAILURE = "GET_ALL_SEARCH_RESULTS_FAILURE";

export const SEARCH_INPUT_CHANGE = "SEARCH_INPUT_CHANGE";

export const GET_PERFORMANCE_SUCCESS = "GET_PERFORMANCE_SUCCESS";
export const GET_PERFORMANCE_FAILURE = "GET_PERFORMANCE_FAILURE";

export const GET_PERFORMANCE_IN_CLASS_SUCCESS = "GET_PERFORMANCE_IN_CLASS_SUCCESS";
export const GET_PERFORMANCE_IN_CLASS_FAILURE = "GET_PERFORMANCE_IN_CLASS_FAILURE";

export const UPDATE_PROFILE_SUCCES = "UPDATE_PROFILE_SUCCES";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const UPDATE_PROFILE_PIC_SUCCESS = "UPDATE_PROFILE_PIC_SUCCESS";
export const UPDATE_PROFILE__PIC_FAILURE = "UPDATE_PROFILE__PIC_FAILURE";

export const ADD_RECENT_ACTIVITIES_SUCCESS = "ADD_RECENT_ACTIVITIES_SUCCESS";
export const ADD_RECENT_ACTIVITIES_FAILURE = "ADD_RECENT_ACTIVITIES_FAILURE";

export const GET_ALL_SUBJECT_PROGRESSES_SUCCESS = "GET_ALL_SUBJECT_PROGRESSES_SUCCESS";
export const GET_ALL_SUBJECT_PROGRESSES_FAILURE = "GET_ALL_SUBJECT_PROGRESSES_FAILURE";

export const ADD_SUBJECT_PROGRESS_SUCCESS = "ADD_SUBJECT_PROGRESS_SUCCESS";
export const ADD_SUBJECT_PROGRESS_FAILURE = "ADD_SUBJECT_PROGRESS_FAILURE";

export const ACCEPT_REJECT_CLASSMEMBER_SUCCESS = "ACCEPT_REJECT_CLASSMEMBER_SUCCESS";
export const ACCEPT_REJECT_CLASSMEMBER_FAILURE = "ACCEPT_REJECT_CLASSMEMBER_FAILURE";

export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_FAILURE = "ADD_CLASS_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";